module.exports = app => {
    const { router, controller } = app;
    router.all('/admin/login', controller.admin.login);
    router.all('/admin/registy', controller.admin.registy);
    router.all('/admin/add', controller.admin.add);
    router.all('/admin/error', controller.admin.error);
    router.all('/admin/load', controller.admin.load);
    router.all('/admin/todayPv', controller.admin.todayPv);
    router.all('/admin/yesterDayPv', controller.admin.yesterDayPv);
    router.all('/admin/todayBug', controller.admin.todayBug);
    router.all('/admin/yesterDayBug', controller.admin.yesterDayBug);
    router.all('/admin/pvList', controller.admin.pvList);
    router.all('/admin/bugList', controller.admin.bugList);
    router.all('/admin/getTodayIp', controller.admin.getTodayIp);
    router.all('/admin/getYesterDayIp', controller.admin.getYesterDayIp);
    router.all('/admin/getBehaviorList', controller.admin.getBehaviorList);
    router.all('/admin/getBehaviorDetail', controller.admin.getBehaviorDetail);
    router.all('/admin/getPageList', controller.admin.getPageList);
    router.all('/admin/ipList', controller.admin.ipList);
    router.all('/admin/ipMapList', controller.admin.ipMapList);
    router.all('/admin/performance', controller.admin.performance);
    router.all('/admin/slowPerformance', controller.admin.slowPerformance);
    router.all('/admin/performanceList', controller.admin.performanceList);
    router.all('/admin/slowPerformanceList', controller.admin.slowPerformanceList);
    router.all('/admin/performanceDetail', controller.admin.performanceDetail);
    router.all('/admin/addEmail', controller.admin.addEmail);
    router.all('/admin/showEmail', controller.admin.showEmail);
    router.all('/admin/addProject', controller.admin.addProject);
    router.all('/admin/showProject', controller.admin.showProject);
    router.all('/admin/updateProject', controller.admin.updateProject);
    router.all('/admin/deleteProject', controller.admin.deleteProject);
    router.all('/admin/redis', controller.admin.redis);
    router.all('/admin/email', controller.admin.email);
};
